version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reseau_social
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - laravel
    volumes:
      - db_data:/var/lib/mysql

networks:
  laravel:

volumes:
  db_data:
